import React from 'react';
import { motion } from 'motion/react';

export const About: React.FC = () => {
  return (
    <section className="py-32 px-6 max-w-7xl mx-auto">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
        <motion.div
          initial={{ opacity: 0, x: -30 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
        >
          <h2 className="text-xs uppercase tracking-[0.5em] text-suri-green mb-6 font-bold">ABOUT</h2>
          <h3 className="text-4xl md:text-6xl font-bold mb-8 leading-tight">
            A TERRITORY WHERE SYMBOLS ARE ALIVE.
          </h3>
          <p className="text-suri-cream/70 text-lg leading-relaxed mb-8">
           Suri Dimension is a parallel dimension in constant movement.<br />
           They grow, expand, attach to the geography, and reorganize over time.<br />
           Mountains can extend.<br />
           Structures can multiply.<br />
           Clouds can be generated by active entities.<br />

           The “party” represents the natural state of activation of the dimension.<br />

           Movement. Rhythm. Variation. Interaction.<br /><br />

           Suri Dimension is always happening. </p>
          <div className="flex gap-8">
            <div>
              <div className="text-3xl font-bold text-suri-yellow mb-1">2000</div>
              <div className="text-[10px] uppercase tracking-widest text-suri-cream/40">Unique Editions</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-suri-red mb-1">150+</div>
              <div className="text-[10px] uppercase tracking-widest text-suri-cream/40">Hand-drawn Traits</div>
            </div>
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 1 }}
          className="relative aspect-square flex items-center justify-center"
        >
          <img 
            src="/images/Yukk-Magic.gif" 
            alt="Yukk Magic" 
            className="w-full h-full object-contain"
            referrerPolicy="no-referrer"
          />
        </motion.div>
      </div>
    </section>
  );
};
